name: NuGet Publish

on:
  push:
    branches: [ master ]

env:
  NUGET_DIR: ${{ github.workspace }}/nuget
  NUGET_ARTIFACT: nuget

jobs:
  testing:
    if: contains(github.event.head_commit.message, 'chore(release)') 
    uses: ./.github/workflows/test.yml

  pack: 
    if: contains(github.event.head_commit.message, 'chore(release)') 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3

      - run: dotnet pack --configuration Release --output ${{ env.NUGET_DIR }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.NUGET_ARTIFACT }}
          path: ${{ env.NUGET_DIR }}
          if-no-files-found: error
          retention-days: 1

  validate-nuget:
    runs-on: ubuntu-latest
    needs: pack
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.NUGET_ARTIFACT }}
          path: ${{ env.NUGET_DIR }}

      - name: Install nuget validator
        run: dotnet tool update Meziantou.Framework.NuGetPackageValidation.Tool --global

      - name: Validate nuget package
        run: meziantou.validate-nuget-package $(ls ${{ env.NUGET_DIR }}/*.nupkg | head -n 1)
        continue-on-error: true # TODO: remove this line when all packages are valid

  publish:
    runs-on: ubuntu-latest
    needs: [validate-nuget, testing]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.NUGET_ARTIFACT }}
          path: ${{ env.NUGET_DIR }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3

      - name: Publish nuget package
        run: dotnet nuget push $(ls ${{ env.NUGET_DIR }}/*.nupkg | head -n 1) --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate

  

